# Generated by Django 4.2.3 on 2023-07-18 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0002_alter_message_dispatch_alter_message_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='filer',
            new_name='filter',
        ),
    ]
